### ISSUE TITLE
Method to deploy code to docker on pi

### ISSUE THREAD

**Issue by sjefferson99** [somakeit/smib#8]
Docker configuration for local deployment. #22 covers distributing this in a registry.

**Comment by sjefferson99** [comment]
Added PoC Dockerfile to the branch for the slack app. As you can see it's basic, but simple is good and iterate improvements.
As it stands I have hard coded the pip installs in the dockerfile as poetry is a whole new level of PITA in docker and I couldn't easily get it working. Given the dependencies are managed by docker build, maybe this is better anyway?

**How to build and launch:**
- Ensure Dockerfile is in smib directory
- ```docker build -t smib-slack .```
- ```docker run --rm -it  smib-slack:latest ``` or ```docker run smib-slack:latest```


**Improvements are many yet:**
- I built this on the Pi which is slow (good few mins) but I think you can configure an arm cross compiler
- Have to build on or build elsewhere and manually distribute file onto Pi, I think you can add to a registry (not sure if needs private cloud or can - use public registry) which would make this easier.
- Have to build another container to execute the webserver, but I think you can override the CMD in the dockerfile on the container start, so same container different command option
- The slack server doesn't actually start due to a port conflict, same as my desktop linux host, will need troubleshooting.
- This approach doesn't cache pip installs when making minor changes later in the dockerfile, pretty certain it's possible to do this in a variety of ways to improve docker build times when code changes
- Pin pip install versions or find a way to get poetry working

**Comment by samcorky** [comment]
@sjefferson99 

I have managed to get this all working in my own branch (`sam-8-method-to-deploy-code-to-docker-on-pi`).  Some minor code changes were made to the websocket server.

The port conflict was due to a glitch in the injectable package running a singleton twice! (tweaked code and now works).

To run:

1. Copy the source code to the machine:
   - smib/ directory
   - pyproject.toml
   - poetry.lock
   - 2 .Dockerfiles
   - docker-compose.yml
2. run `docker compose up -d` or `docker compose up -d  --build` (to force rebuild)

This takes a few minutes but does start up and connect the 2 containers properly.

My branch is based on the logging branch btw 😄 

I like your idea of the single container with different command entry points!

**Comment by samcorky** [comment]
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

Can host docker registry with GIT

**Comment by sjefferson99** [comment]
OK, so in theory the web socket and docker issues will be closed when we merge your docker branch (I will delete my docker branch if you've taken the POC further on yours), will need to associate the websocket issue with that branch if so. Then we need to work out what we can test and push in to dev so we have less stuff flying around. In theory should all merge OK, but the longer we have multiple issues and branches being developed the greater the chance of fun conflicts. Hopefully get a lot of stuff merged into develop tomorrow evening. I'll see if I can test this docker branch for the above.

**Comment by samcorky** [comment]
Possible poetry docker build enhancements as per https://medium.com/@albertazzir/blazing-fast-python-docker-builds-with-poetry-a78a66f5aed0

**Comment by sjefferson99** [comment]
Promising looking article, will give it a read when possible although assume 3Am commit with implementation will arrive before then.
